server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 # 设置拉取注册中心服务的间隔时间为5秒
zuul:
  prefix: /api
  routes:
    item-service: /item/** # 路由到商品的微服务
    search-service: /search/** # 路由到搜索微服务
    user-service: /user/** # 路由到用户服务
    auth-service: /auth/** # 路由到授权中心服务
    cart-service: /cart/** # 路由到购物车服务
    order-service: /order/**
  add-host-header: true
  sensitive-headers:  # 覆盖默认敏感头信息
leyou:
  jwt:
    pubKeyPath: C:\\idea-project\\leyou\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item