server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: lihongji
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.126.131
  rabbitmq:
    host: 192.168.126.131
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
mybatis:
  type-aliases-package: com.leyou.user.pojo